### ISSUE TITLE
Please update to 1.21.

### ISSUE THREAD

**Issue by TheFaik** [IPECTER/RTUBiomeLib#42]
Please update to 1.21.

**Comment by alvindimas05** [comment]
Hey, you might want to use my updated version since the dev is probably busy.

https://github.com/alvindimas05/RTUBiomeLib/releases/tag/1.9.2

**Comment by TheFaik** [comment]
> Hey, you might want to use my updated version since the dev is probably busy.
> 
> https://github.com/alvindimas05/RTUBiomeLib/releases/tag/1.9.2

Thanks!

**Comment by IPECTER** [comment]
> Hey, you might want to use my updated version since the dev is probably busy.
> 
> https://github.com/alvindimas05/RTUBiomeLib/releases/tag/1.9.2

thx for fork.
I merged it.

**Comment by alvindimas05** [comment]
> > Hey, you might want to use my updated version since the dev is probably busy.
> > https://github.com/alvindimas05/RTUBiomeLib/releases/tag/1.9.2
> 
> thx for fork. I merged it.

You're welcome. Also, you might want to edit the README since I changed it.

**Comment by TheFaik** [comment]
> Hey, you might want to use my updated version since the dev is probably busy.
> 
> https://github.com/alvindimas05/RTUBiomeLib/releases/tag/1.9.2

Please update your plugin
