### ISSUE TITLE
Please update to 1.21.1)

### ISSUE THREAD

**Issue by TheFaik** [IPECTER/RTUBiomeLib#45]
Please update plugin to 1.21.1)

**Comment by All4getMe** [comment]
I think the plugin in the "Stable" branch already has support for version 1.21.1, but in version 1.9.2 it does not. I need to build plugin sources (I can't do it my computer spent an hour processing nms modules and finally gave an error. Probably should use a different version of java)

**Comment by IPECTER** [comment]
use 1.9.3
